package main

// There are three files (or decks) of cards in this file: constantsAndSuch.go
// Firstly, we have fileOfCardsS which is used in exorcises 8 and 9, the sequentials (aCardS)
// Then, there is fileOfCardsMostDifficult which is used in exorcise 7 (aCardD)
// Lastly, comes fileOfCards which is used in all other exorcises (aCard)
//
// The last two decks will be read randomly
// The first of the three decks will be read sequentially
//
var aCardS = charSetStruct{}

var fileOfCardsS = []charSetStruct{

	{"ザ", "ざ", "za", "zaザ", "ざ",
		" sa-->za:ざ  dakuten  濁点",
		" sa-->za   za:ザ:ざ  so it still protrudes to the left",
		" TT: down on the 'X' char plus a dakuten 濁点 for sa-->za",
		" ?:ざ:ザ  TT: down on the 'X' char, plus a dakuten 濁点"},

	{"デ", "で", "de", "deデ", "で",
		" de:で:デ ",
		" de from ta-->da , plus a dakuten 濁点",
		" TT: left-ring to the 'W' char, plus a dakuten 濁点",
		" ?:で:デ  , plus a dakuten, TT: L-ring to the 'W' char, plus a dakuten 濁点"},

	{"セ", "せ", "se", "seセ", "せ",
		" se:せ:セ  ... セ is just a bit more angular, as is the way with most Katakana ",
		" se:せ looks like a face saying something ... 'se'ing something ",
		" TT: right-pinky to the 'P' char",
		" ?:せ:セ  TT: R-pinky to the 'P' char,  セ is more angular, as with most Katakana"},

	{"キ", "き", "ki", "kiキ", "き",
		" ki:き:キ ... is an easy one!   キ has the same top as ki:き, and they look like 'keys' ",
		" ki:き ... they both have the same top:  き キ  looks like a chi-key",
		" TT: L-index> to the 'G' char,  Think: ki-of-G  き,  Compare:  sa:さ-ki:き  さき ... saki ",
		"き:キ  TT: L-index > to the 'G' char,  キ same top as き, looks like a 'chi-key'"},

	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra is usually pronounced as la",
		" TT: right-ring up to the 'O' char",
		" Compare:  fu:フ, u:ウ:う,  & our:ラ:ら:?  TT: right-ring up to the 'O' char"},

	{"ダ", "だ", "da", "daダ", "だ",
		" ta-->da  だ:ダ ",
		" da is ta with a dakuten 濁点",
		" TT: left-pinky to the 'Q' char",
		" だ:ダ  ta-->?  TT: left-pinky to the 'Q' char, plus a dakuten 濁点"},

	{"ブ", "ぶ", "bu", "buブ", "ぶ",
		" bu:ブ:ぶ",
		" fu-->bu , plus a dakuten 濁点",
		" TT: left-ring to the '2' char is fu-->bu",
		" ブ:ぶ   TT: left-ring to the '2' char, plus a dakuten 濁点 :: fu-->?"},

	{"サ", "さ", "sa", "saサ", "さ",
		" sa:さ:サ , if you 'se':せ そサ ,  Compare:  Hira se:せ  to  Kata sa:サ  せサ ",
		" ... , but it looks an awful-lot like Hira se:せ, I'd say   ... just 'Hir'-say ?? ",
		" TT: ring>v to the 'X' char  --  at least Kata 'sa' still goes to the left ... ",
		" さ:サ ,  Compare:  Hira:se:せ  to  Kata:?:サ  せサ se:? TT: ring>v to the 'X' char"},

	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" ?:そ:ソ  ,  Compare:  n:ん:ン     TT: L-index<-- to the 'C' char"},

	{"マ", "ま", "ma", "maマ", "ま",
		" ma:マ:ま ",
		" mama is using a brest pump ",
		" TT: right-index on the 'J' char :: ma",
		" ?:マ:ま   lady is using a brest pump    TT: right-index on the 'J' char"},

	{"ゼ", "ぜ", "ze", "zeゼ", "ぜ",
		" sa-->za   se-->ze , plus a dakuten 濁点",
		" ze:ゼ:ぜ",
		" TT: pinky to the 'P' char, plus a dakuten 濁点   ze:ゼ:ぜ",
		" ?:ゼ:ぜ   TT: pinky to the 'P' char, plus a dakuten 濁点   sa-->za  se:? "},

	{"チ", "ち", "chi", "chiチ", "ち",
		" chi:ち:チ ,   ち チ ",
		" ...  chi:ち:チ ,  Compare:  chi:チ  te:テ ",
		" TT: left-pinky on the 'A' char ",
		" ?:ち:チ   Kata bares 'some' resemblance to ち   TT: L-pinky on the 'A' char "},

	{"ヌ", "ぬ", "nu", "nuヌ", "ぬ",
		" nu:ぬ:ヌ   Compare:  me:メ  &  na:ナ ",
		" nu flew ヌ -- till it hit a ceiling ",
		" TT: R-ring<--- to the '1' char, at least two lines cross, nu flew ヌ -- hit a ceiling ",
		" ?:ぬ:ヌ   ?-flew ヌ -- till it hit a ceiling  TT: R-ring<--- to the '1' char"},

	{"ニ", "に", "ni", "niニ", "に",
		" ni:に:ニ  I can see a knee-cap in the Hiragana ",
		" ni:に:ニ  ",
		" TT: right-middle< to the 'I' char ",
		" ?:に:ニ  TT: R-middle< to the 'I' char,  I can see a knee-cap in the Hiragana "},

	{"ピ", "ぴ", "pi", "piピ", "ぴ",
		" pi:ピ:ぴ  ",
		" hi-->pi  becomes with a handakuten゜半濁点",
		" TT: L-index to the 'V' char, plus a handakuten゜半濁点",
		" ?:ピ:ぴ   TT: L-index to the 'V' char, plus a handakuten゜半濁点"},

	{"ホ", "ほ", "ho", "hoホ", "ほ",
		" ho:ホ:ほ  looks like a hoe in a dress",
		" ho",
		" TT: right-ring-way-up to the '-' char",
		" ?:ホ:ほ   TT: right-ring-way-up to the '-' char"},

	{"ケ", "け", "ke", "keケ", "け",
		" ke:け:ケ  bits of it are there, just as many curves though ,  Compare to:  ku:ク  ta:タ ",
		" ke:け  ... looks enough like a Keg ...  Foam-ment THAT image in your brain ",
		" TT: right-pinky-> one-over to the ':*' chars   け:ケ ",
		"け:ケ  bits still there  Compare:  ku:ク  ta:タ  クケタ  TT: R-pinky-> to the ':*' chars"},

	{"ロ", "ろ", "ro", "roロ", "ろ",
		" ro:ロ:ろ  no loop on ro:ろ  Compare ru:る",
		" ro",
		" TT: right-pinky slide down --> right of the '?' char",
		" Looks like a square O,  TT: right-pinky slide down --> right of the '?' char"},

	{"バ", "ば", "ba", "baバ", "ば",
		" ba:バ:ば  ha-->ba-->pa   dakuten 濁点, handakuten゜半濁点",
		" ba",
		" TT: L-index on the 'F' char, plus a dakuten 濁点 ",
		" ?:バ:ば  ha-->?  TT: L-index on the 'F' char, plus a dakuten 濁点"},

	{"タ", "た", "ta", "taタ", "た",
		" ta:た:タ  ... it's a ku:くク with a drool クタ... and that's くool I guess ",
		" ta:た:タ ,  Compare:  ku:ク  &  ke:ケ ",
		" TT: left-pinky< to the 'Q' char ",
		" top of タ looks like た,  more than ku:ク looks like く  TT: L-pinky< to the 'Q' char"},

	{"ユ", "ゆ", "yu", "yuユ", "ゆ",
		" yu:ユ:ゆ  Katakana looks like number 1, you are #1 ",
		" yu",
		" TT: on the '8' char, shiftless when naked  ",
		" ?:ユ:ゆ  TT: on the '8' char, shiftless when naked "},

	{"パ", "ぱ", "pa", "paパ", "ぱ",
		" pa:パ:ぱ  ha-->ba-->pa   dakuten 濁点, handakuten゜半濁点",
		" pa",
		" TT: left-index on the 'F' char, plus a handakuten 半濁点",
		" ha-->?  TT: L-index on the 'F' char, plus a handakuten 半濁点"},

	{"ト", "と", "to", "toト", "と",
		" to:と:ト   Kata 'toe' is flipped-out. Kicked in the balls. on its head: と -> ト ",
		" Katakana to:と is flipped-out. Kicked in the balls, On its head ",
		" TT: left-ring on the 'S' char, Kata toe is flipped-out. Kicked on its head: と -> ト ",
		" Kata char was kicked on its head: と --> ト  TT: L-ring on the 'S' char"},

	{"ポ", "ぽ", "po", "poポ", "ぽ",
		" po:ポ:ぽ  ho-->bo-->po  dakuten, handakuten゜半濁点",
		" po",
		" TT: right-ring-way-up to the '-' char, plus a handakuten゜半濁点",
		" ?:ポ:ぽ   TT: right-ring-way-up to the '-' char, plus a handakuten゜半濁点"},

	{"ア", "あ", "a", "aア", "あ",
		" a:あ:ア  ahh-'no-got-stabbed',  Compare: me:め  a:あ  nu:ぬ  ne:ね    あア-Fuck-mae-te:て!",
		" The Kata a:ア looks nothing-like the hiragana あ, but like hira te:て   あア-Fuck-mae-te:て! ",
		" TT: left-middle<- to the '3' char for あ:ア  ?is maybe a grotesque A:ア ?? ",
		" Compare:  me:め  あ  nu:ぬ  ne:ね   あ-Fuck mae-te!  TT: L-middle<- to the '3' char"},

	{"オ", "お", "o", "oオ", "お",
		" o:お:オ , and オ does have a vague resemblance, albeit with less curves: お オ",
		" o:お , for the Kata オ ... think: someone is 'on-the-go' ... see the fl'o'w ",
		" TT: index--> to the '6' char     o:お:オ ",
		" お:オ, on-the-go', cloak trailing behind   TT: index--> to the '6' char"},

	{"ク", "く", "ku", "kuク", "く",
		" ku:く:ク ,  Kata: starting with one angle, they settled for this??  く:ク ",
		" ku:く:ク ,  Compare:  ta:タ  ke:ケ  ku:ク  クケタ,  it's kuku, kookoo I tell you! ",
		" TT: R-index<- to the 'H' char  く:ク ",
		"く:ク ,  Compare:  クケタ ta:タ  ke:ケ  ?:ク   TT: R-index<- to the 'H' char"},

	{"メ", "め", "me", "meメ", "め",
		" me:メ:め   Compare: nu:ヌ",
		" me",
		" TT: right-pinky-slide down to the '?' char",
		" メ:め messy-lesser ver of nuddle:ぬ　 TT: R-pinky-slide down to the '?' char"},

	{"ヨ", "よ", "yo", "yoヨ", "よ",
		" yo:ヨ:よ  Looks like a toy",
		" yo",
		" TT: right-middle to the '9' char, un-shifted",
		" ヨ:よ  Looks like a toy  TT: right-middle to the '9' char, un-shifted"},

	{"ル", "る", "ru", "ruル", "る",
		" ru:ル:る  ru-two, and the Hira has a luup for ru ",
		" ru",
		" TT: right-pinky-slide under to the left, on the '.' char",
		" ル:る  ?:two    TT: right-pinky-slide under to the left, on the '.' char"},

	{"テ", "て", "te", "teテ", "て",
		" te:て:テ  Looks like a T",
		" te:て:テ ,  Compare:  chi:チ & te:テ:て ",
		" TT: left-ring< to the 'W' char, te:テ:て  went the wrong way, and gained a flat hat ",
		" ?:て:テ ,  Compare:  chi:チ & テ:て  TT: left-ring< to the 'W' char"},

	{"カ", "か", "ka", "kaカ", "か",
		" ka:か:カ ... is an easy one!  It simply looks like a 'K' ",
		" ... Kata is the same カ , albeit more-angular and with one-less line to draw than か ",
		" TT: left-index--> to the 'T' char   か or カ",
		" か:カ ... looks like a 'K'    TT: left-index--> to the 'T' char"},

	{"ヤ", "や", "ya", "yaヤ", "や",
		" ya:ヤ:や  look very similar, which is too rare",
		" ya",
		" TT: right-index to the '7' char, un-shifted",
		" ヤ:や   TT: right-index to the '7' char, un-shifted"},

	{"ミ", "み", "mi", "miミ", "み",
		" mi:ミ:み  mi is three, or phallic 'me' is mi ",
		" mi is three; lines",
		" TT: right-index to the 'N' char",
		" ミ:み   TT: right-index to the 'N' char"},

	{"エ", "え", "e", "eエ", "え",
		" e:え:'エ' does have a vague, angular resemblance: eye see it as an, eye; may-bey, may-b-eh e ",
		" e:え ... see 'エ' as a ... an ... eye eh; may-bey, m'ay'-b-eh e   e:え:エ ",
		" TT: left-index> to the '5' char   e:え:エ ",
		" エ:え   TT: L-index> to the '5' char,  エ, eye see it as a ... an, eye ??  eh?:え:エ"},

	{"ゴ", "ご", "go", "goゴ", "ご",
		" go:ご:ゴ   looks like two Koy fish ko-y, and as ka-->ga, ko-->go ",
		" go:ご:ゴ    ご:ゴ makes sense, 'cause angles'",
		" TT: index <--- to the 'B' char, plus a dakuten 濁点  ご",
		" ご:ゴ  TT: index <--- to the 'B' char, plus a dakuten 濁点 ka,ki,ku,ke,ko-->ga,gi,gu,ge,?"},

	{"ギ", "ぎ", "gi", "giギ", "ぎ",
		" gi:ぎ:ギ is an easy Kata, ギ has the same top as ki:き, and is NEVER from shi:し ",
		" ぎ:ギ is always the sound gi, and is Seldom ji ( that usually being じ:ji:ジ )",
		" TT: L-index on 'G' char, plus a dakuten 濁点, ぎ:ギ, compare to za:ざ from sa:さ",
		" ぎ:ギ  TT: 'G' char,  sound is from き ,and NEVER from し or ち  ka-->ga,?,gu,ge,go"},

	{"ウ", "う", "u", "uウ", "う",
		" u:う:ウ , they just added angles for the Kata -- looks like the wa:ワ albeit with a mohawk ' ",
		" u:ooh:lays-atop tsu:つ  u:ウ is more-angular with a tick for its top line ",
		" TT: L-middle> to the '4' char  う : Kata looks like the wa:ワ albeit with a mohawk ' ",
		" う:ウ ,  TT: left-middle> to the '4' char, う:ウ not ra:ら | wa:ワ with a mohawk"},

	{"ビ", "び", "bi", "biビ", "び",
		" bi:ビ:び   hi-bi-pi ",
		" bi is from hi which looks like a smiling hi-hi びび",
		" TT: L-index to the 'V' char, plus a dakuten 濁点",
		" ?:ビ:び from hi, looks like smiling hi-hi びび   TT: L-index to 'V' char, plus a dakuten"},

	{"ジ", "じ", "ji", "jiジ", "じ",
		" ji:ジ:じ    Seldom is it fr chi:ち ,it's the sound ji, NEVER gi (that being ぎ:gi:ギ)",
		" ji, the sound, VERY RARELY is from chi:ち:ヂ ,but NEVER the sound gi (that being ぎ:gi:ギ)",
		" TT: 'D' char, remember, the sound:ji is nearly-always from shi:し with a dakuten 濁点 じ:ジ",
		" ジ:じ  TT: 'D' char, with a dakuten 濁点     it's the sound:gee:jeep"},

	{"イ", "い", "i", "iイ", "い",
		" i:イ:い  the Kata イ looks more like a hiragana te:て, but still two mostly-vertical lines: イ",
		" i:い:イ  for the Kata ... maybe shift the two lines of the hiragana い to forms an 'I'  i:イ",
		" TT: left-middle< to the 'E' char  い:イ ",
		" い:イ at least it is still two mostly-vertical lines   TT: L-middle< to the 'E' char"},

	{"ス", "す", "su", "suス", "す",
		" su:す:ス ",
		" ス sue:す looks like she is running (and they were looking for angles)",
		" TT: left-index < to the 'R' char,  (sue is running ス)",
		" ス:す  she is running  TT: left-index < to the 'R' char"},

	{"ゲ", "げ", "ge", "geゲ", "げ",
		" ge:げ:ゲ bits still there (as many curves though)  Compare  ku:gu:グ,  &  ta:za:ダ",
		" ge:げ Compare to ku:gu:グ, and ta:za:ダ   don't forget the dakuten 濁点",
		" TT: ':*' chars, 濁点    げ:ゲ  ダグゲ    ka,ki,ku,ke,ko-->ga,gi,gu,?,go  濁点",
		" げ:ゲ   TT: L-pinky> to ':*' chars   げ Compare to ku:gu:グ, and ta:da:ダ "},

	{"ネ", "ね", "ne", "neネ", "ね",
		" ne:ね:ネ  Kata looks like a hoe that got nailed ネ ",
		" something got nailed-down by that spike at the left ",
		" TT: R-ring<v to the ',<' chars  ...  Yea, to me it is a hoe:ほ that got nailed ネ ",
		" ?:ね:ネ  Kata looks like a hoe that got nailed ネ  TT: R-ring<v to the ',<' chars"},

	{"モ", "も", "mo", "moモ", "も",
		" mo:モ:も ",
		" mo",
		" TT: right-middle<v to the 'M' char",
		" モ:も   TT: right-middle<v to the 'M' char,  m is for ?"},

	{"ナ", "な", "na", "naナ", "な",
		" na:な:ナ  Kata ナ is just like the left side of the Hira な -- な:ナ ",
		" na:な:ナ , Compare:  na:ナ  me:メ  nu:ヌ  ( め ぬ )",
		" TT: index< to the 'U' char,  ナ is very simple ... na-t complex at-all :: な ",
		" な:ナ  TT: index< to the 'U' char, Hiragana t-ies a knot, see the two chars thar "},

	{"ン", "ん", "n", "nン", "ん",
		" n:ン:ん  looks like a cursive n, and sounds like it too",
		" n",
		" TT: index to the 'Y' char",
		" ン:ん   TT: index to the 'Y' char, sounds the way it looks"},

	{"ヘ", "へ", "he", "heヘ", "へ",
		" he:ヘ:へ  Hira and Kata are pretty-much the same, both hay:he stacks",
		" he",
		" TT: left-pinky way-up to the '^' char",
		" ヘ:へ   TT: left-pinky way-up to the '^' char, clearly stacks of feed"},

	{"ズ", "ず", "zu", "zuズ", "ず",
		" zu:ず:ズ:づ:ヅ: , is either ず:ズ or づ:ヅ , as they are both the same sound",
		" zu: 'Sue' ズ is running with her hair flowing behind her (from su:す) ",
		"  TT: L-index< to the 'R' char, same sound: a big wave つ  or a  snake ず at the zoo",
		" ?:ず:ズ づ:ヅ  same sound   TT: left-index< to the 'R' char, dakuten 濁点 "},

	{"ド", "ど", "do", "doド", "ど",
		" do:ド:ど   ta-->da  to --> do    plus a dakuten 濁点",
		" do:ど:ド ",
		" TT: left-ring on the 'S' char, plus a dakuten 濁点 ",
		" ?:ど:ド  TT: left-ring on the 'S' char, plus a dakuten 濁点   ta-->da  to-->? "},

	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},

	{"ペ", "ぺ", "pe", "peペ", "ぺ",
		" pe:ペ:ぺ  same same, , clearly stacks of feed, hay:he stacks, handakuten゜半濁点",
		" pe:  he-->be-->pe , dakuten 濁点, handakuten゜半濁点",
		" TT: left-pinky way-up to the '^' char, plus handakuten゜半濁点",
		" ペ:ぺ   TT: left-pinky way-up to the '^' char, stack of feed, handakuten゜半濁点"},

	{"ノ", "の", "no", "noノ", "の",
		" no:の:ノ   it looks like a 'no' symbol ",
		" no:の:ノ  and the Kata retains the slash ",
		" TT: right-middle on 'K' char",
		" ?:の:ノ  TT: right-middle on 'K' char   ?-thank-you "},

	{"ヲ", "を", "wo", "woヲ", "を",
		" wo:ヲ:を   Compare: fu:フ　wa:ワ　u:ウ　a:ア　te:テ:て　 ",
		" wo:ヲ, at least it looks something like wa:ワ, though shifted",
		" TT: right-ring up to the '0' char (shifted)",
		" ヲ:を   Compare: wa:ワ   TT: right-ring up to the '0' char (shifted)"},

	{"ヅ", "づ", "zu", "zuヅ", "づ",
		" zu:づ:ヅ ず:ズ , is either ず:ズ or づ:ヅ , as they are both the same sound ",
		" zu: for the Kataす think 'Sue' ズ is running with her hair flowing behind her",
		" TT: L-pinky>v to the 'Z' char, plus dakuten 濁点 ",
		" ?:づ:ヅ ず:ズ  that big wave つ sounds the same, TT: L-pinky>v to the 'Z' char"},

	{"ム", "む", "mu", "muム", "む",
		" mu:ム:む  somehow, it does look like a cow",
		" mu",
		" TT: right-pinky way-over to the '}]' chars",
		" ム:む   TT: right-pinky way-over to the '}]' chars"},

	{"シ", "し", "shi", "shiシ", "し",
		" shi:し:シ  'she' sleeps & snores゛,  Compare: tsu:ツ & so:ソ　to the more-laid-back shi:シ ",
		" shi:し:シ  し looks like a sheep hook,  Compare: ツシ  tsu-shi ",
		" TT: on the 'D' char, シ 'she' is sleeping/snoring,  (no angles here, less curve though)",
		" し:シ  TT: on the 'D' char   Compare: tsu:ツ  & so:ソ　to the more-laid-back シ:し"},

	{"グ", "ぐ", "gu", "guグ", "ぐ",
		" gu:ぐ:グ Starting with one angle, they settled for this?  Compare:  ta:da:ダ, and ke:ge:ゲ",
		" gu:ぐ:グ  Compare:  da:ダ, ge:ゲ    ダグゲ　",
		" TT: R-index to 'H' char, plus dakuten 濁点     ka,ki,ku,ke,ko-->ga,gi,gu,ge,go",
		" ぐ:グ  TT: R-index to 'H' char, plus dakuten 濁点   Compare:  da:ダ, ge:ゲ  ダグゲ  "},

	{"リ", "り", "ri", "riリ", "り",
		" ri:リ:り  actually, very very similar, actually!",
		" ri",
		" TT: left-ring-finger on it's 'L' char",
		" リ:り very similar   TT: left-ring-finger on it's 'L' char"},

	{"ヒ", "ひ", "hi", "hiヒ", "ひ",
		" hi:ひ:ヒ  a smiling mouth doing a hee-hee hi-hi",
		" hi, pronounced hee ",
		" TT: left-index > to the 'V' char",
		" ?:ひ:ヒ   '?'-man   TT: left-index > to the 'V' char"},

	{"ゾ", "ぞ", "zo", "zoゾ", "ぞ",
		" zo:ぞ:ゾ  it's soo big!   Compare: n:ん:ン which lays-down more",
		" zo:ぞ:ゾ  long hair and a big one,  Compare:  し:シ  &  no:ノ,  or  n:ん:ン ",
		" TT: left-index <-- to the C char, plus a dakuten 濁点 , a big one!",
		" ?:ぞ:ゾ  TT: left-index <-- to the C char, not no:ノ | n:ん:ン which lays-down more"},

	{"ベ", "べ", "be", "beベ", "べ",
		" be:ベ:べ  same same, , clearly stacks of feed, hay:he stacks, ",
		" be:  he-->be-->pe , dakuten 濁点, handakuten゜半濁点",
		" TT: left-pinky way-up to the '^' char, plus dakuten 濁点",
		" TT: left-pinky way-up to the '^' char, plus dakuten 濁点   stack of feed, "},

	{"ワ", "わ", "wa", "waワ", "わ",
		" wa:ワ:わ  Water-fall, pissing in the wind (making わしこ) ",
		" wa",
		" TT: right-ring to the '0' char",
		" ワ:わ  aqua-fall   TT: right-ring to the '0' char"},

	{"レ", "れ", "re", "reレ", "れ",
		" re:レ:れ  laying on the little finger",
		" re:レ:れ  the れ looks like someone getting blown, laid ",
		" TT: left-pinky on it's ';' char",
		" レ:れ   TT: left-pinky on it's ';' char"},

	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},

	{"ボ", "ぼ", "bo", "boボ", "ぼ",
		" bo:ボ:ぼ  looks like a hoe in a dress, ho-->bo-->po  dakuten, handakuten゜半濁点",
		" bo",
		" TT: right-ring-way-up to the '-' char, plus dakuten 濁点",
		" ボ:ぼ  TT: right-ring-way-up to the '-' char, plus dakuten 濁点"},

	{"ガ", "が", "ga", "gaガ", "が",
		" ga:ガ:が  same ガ albeit more angular with one-less line to draw than が",
		" ga:が is an easy one. ka--> ga,gi,gu,ge,go with a dakuten 濁点",
		" TT: index --> to the 'T' char, plus a dakuten 濁点 ",
		" ガ:が   TT: index --> to the 'T' char,  Kata has one-less line to draw"},

	{"ハ", "は", "ha", "haハ", "は",
		" ha:ハ:は:ha  looks a bit like the letter H, and a ハ ha-haystack ハ ",
		" ha: ハ ha-haystack ハ ",
		" TT: left-index on it's 'F' char",
		" ハ:は   looks a bit like the letter    TT: left-index on it's 'F' char "},

	{"プ", "ぷ", "pu", "puプ", "ぷ",
		" pu:プ:ぷ   ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" pu:fu:  think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" プ:ぷ   TT: left-ring to the '2' char,  it is the big mountain in Japan"},

	{"コ", "こ", "ko", "koコ", "こ",
		" ko:こ:コ ... it makes sense, 'cause angles:  ko:コ ,  Compare:  ni:に:ニ ",
		" ... see the two Koy fish?   'ko'oy fish? ",
		" TT: index <--- to the 'B' char,  ko way-down below  こ ",
		" こ:コ   TT: index <--- to the 'B' char    Compare:  ni:に:ニ"},
}

/*
.
.
.
.
.
.
.
.
.
.
.
.
*/
var aCardD = charSetStruct{}

var fileOfCardsMostDifficult = []charSetStruct{
	{"ワ", "わ", "wa", "waワ", "わ",
		" wa:ワ:わ  Water-fall, pissing in the wind (making わしこ) ",
		" wa",
		" TT: right-ring to the '0' char",
		" ワ:わ  aqua-fall   TT: right-ring to the '0' char"},
	{"ヲ", "を", "wo", "woヲ", "を",
		" wo:ヲ:を   Compare: fu:フ　wa:ワ　u:ウ　a:ア　te:テ:て　 ",
		" wo:ヲ, at least it looks something like wa:ワ, though shifted",
		" TT: right-ring up to the '0' char (shifted)",
		" ヲ:を   Compare: wa:ワ   TT: right-ring up to the '0' char (shifted)"},
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	{"モ", "も", "mo", "moモ", "も",
		" mo:モ:も ",
		" mo",
		" TT: right-middle<v to the 'M' char",
		" モ:も   TT: right-middle<v to the 'M' char,  m is for ?"},
	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},
	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},
	{"ナ", "な", "na", "naナ", "な",
		" na:な:ナ  Kata ナ is just like the left side of the Hira な -- な:ナ ",
		" na:な:ナ , Compare:  na:ナ  me:メ  nu:ヌ  ( め ぬ )",
		" TT: index< to the 'U' char,  ナ is very simple ... na-t complex at-all :: な ",
		" な:ナ  TT: index< to the 'U' char, Hiragana t-ies a knot, see the two chars thar "},
	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},
	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},
	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},
	{"テ", "て", "te", "teテ", "て",
		" te:て:テ ",
		" te:て:テ ,  Compare:  chi:チ テ:て ",
		" TT: ring< to the 'W' char, te:テ:て  went the wrong way, and gained a flat hat ",
		" ?:て:テ ,  Compare:  chi:チ テ:て "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"シ", "し", "shi", "shiシ", "し",
		" shi:し:シ  'she' sleeps & snores゛,  Compare: tsu:ツ & so:ソ　to the more-laid-back shi:シ ",
		" shi:し:シ  し looks like a sheep hook,  Compare: ツシ  tsu-shi ",
		" TT: on the 'D' char, シ 'she' is sleeping/snoring,  (no angles here, less curve though)",
		" し:シ  TT: on the 'D' char   Compare: tsu:ツ  & so:ソ　to the more-laid-back シ:し"},
	{"オ", "お", "o", "oオ", "お",
		" o:お:オ , and オ does have a vague resemblance, albeit with less curves: お オ",
		" o:お , for the Kata オ ... think: someone is 'on-the-go' ... see the fl'o'w ",
		" TT: index--> to the '6' char     o:お:オ ",
		" お:オ, on-the-go, cloak trailing behind ... maybe? "},
	//
	{"ン", "ん", "n", "nン", "ん",
		" n:ン:ん  looks like a cursive n, and sounds like it too",
		" n",
		" TT: index to the 'Y' char",
		" ン:ん   TT: index to the 'Y' char, sounds the way it looks"},
	{"ン", "ん", "n", "nン", "ん",
		" n:ン:ん  looks like a cursive n, and sounds like it too",
		" n",
		" TT: index to the 'Y' char",
		" ン:ん   TT: index to the 'Y' char, sounds the way it looks"},
	{"ア", "あ", "a", "aア", "あ",
		" a:あ:ア  ahh-'no-got-stabbed',  Compare: me:め  a:あ  nu:ぬ  ne:ね    あア-Fuck-mae-te:て!",
		" The Kata a:ア looks nothing-like the hiragana あ, but like hira te:て   あア-Fuck-mae-te:て! ",
		" TT: middle<- to the '3' char for あ:ア  ?is maybe a grotesque A:ア ?? ",
		" Compare:  me:め  あ  nu:ぬ  ne:ね      あ-Fuck-mae-te!"},
	{"ア", "あ", "a", "aア", "あ",
		" a:あ:ア  ahh-'no-got-stabbed',  Compare: me:め  a:あ  nu:ぬ  ne:ね    あア-Fuck-mae-te:て!",
		" The Kata a:ア looks nothing-like the hiragana あ, but like hira te:て   あア-Fuck-mae-te:て! ",
		" TT: middle<- to the '3' char for あ:ア  ?is maybe a grotesque A:ア ?? ",
		" Compare:  me:め  あ  nu:ぬ  ne:ね      あ-Fuck-mae-te!"},
	{"ウ", "う", "u", "uウ", "う",
		" u:う:ウ , they just added angles for the Kata -- looks like the wa:ワ albeit with a mohawk ' ",
		" u:ウ more-angular and with a tick for its top line   Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" TT: middle> to the '4' char  う : Kata looks like the wa:ワ albeit with a mohawk ' ",
		" う:ウ ,  Compare:  wa:ワ cascading wa-ter fall,　um-'ca'y "},
	//
	{"ウ", "う", "u", "uウ", "う",
		" u:う:ウ , they just added angles for the Kata -- looks like the wa:ワ albeit with a mohawk ' ",
		" u:ウ more-angular and with a tick for its top line ",
		" TT: middle> to the '4' char  う : Kata looks like the wa:ワ albeit with a mohawk ' ",
		" う:ウ ,  Compare:  wa:ワ cascading wa-ter fall,　um-'ca'y "},
	//
}

/*
.
.
.
.
.
.
.
.
.
.
*/

var aCard = charSetStruct{}

var fileOfCards = []charSetStruct{
	// Did not work :
	//const fileOfCards = []charSetStruct{

	// vowels: (a-i-u-e-o) ==========================================================================================
	// 2 of あ ア a -- 2 times for a:あ:ア
	{"ア", "あ", "a", "aア", "あ",
		" a:あ:ア  ahh-'no-got-stabbed',  Compare: me:め  a:あ  nu:ぬ  ne:ね    あア-Fuck-mae-te:て!",
		" The Kata a:ア looks nothing-like the hiragana あ, but like hira te:て   あア-Fuck-mae-te:て! ",
		" TT: middle<- to the '3' char for あ:ア  ?is maybe a grotesque A:ア ?? ",
		" Compare:  me:め  あ  nu:ぬ  ne:ね      あ-Fuck-mae-te!"},
	{"ア", "あ", "a", "aア", "あ",
		" a:あ:ア  ahh-'no-got-stabbed',  Compare: me:め  a:あ  nu:ぬ  ne:ね    あア-Fuck-mae-te:て!",
		" The Kata a:ア looks nothing-like the hiragana あ, but like hira te:て   あア-Fuck-mae-te:て! ",
		" TT: middle<- to the '3' char for あ:ア  ?is maybe a grotesque A:ア ?? ",
		" Compare:  me:め  あ  nu:ぬ  ne:ね      あ-Fuck-mae-te!"},
	//
	// 2 of い イ i -- 2 times for i:い:イ
	{"イ", "い", "i", "iイ", "い",
		" i:イ:い  the Kata イ looks more like a hiragana te:て, but still two mostly-vertical lines: イ",
		" i:い:イ  for the Kata ... maybe shift the two lines of the hiragana い to forms an 'I'  i:イ",
		" TT: left-middle< to the 'E' char  い:イ ",
		" い:イ at least it is still two mostly-vertical lines   TT: L-middle< to the 'E' char"},
	{"イ", "い", "i", "iイ", "い",
		" i:イ:い  the Kata イ looks more like a hiragana te:て, but still two mostly-vertical lines: イ",
		" i:い:イ  for the Kata ... maybe shift the two lines of the hiragana い to forms an 'I'  i:イ",
		" TT: left-middle< to the 'E' char  い:イ ",
		" い:イ at least it is still two mostly-vertical lines   TT: L-middle< to the 'E' char"},
	//
	// 2 of u:う:ウ  2 times for u:う:ウ
	{"ウ", "う", "u", "uウ", "う",
		" u:う:ウ , they just added angles for the Kata -- looks like the wa:ワ albeit with a mohawk ' ",
		" u:ウ more-angular and with a tick for its top line   Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" TT: middle> to the '4' char  う : Kata looks like the wa:ワ albeit with a mohawk ' ",
		" う:ウ ,  Compare:  wa:ワ cascading wa-ter fall,　um-'ca'y "},
	//
	{"ウ", "う", "u", "uウ", "う",
		" u:う:ウ , they just added angles for the Kata -- looks like the wa:ワ albeit with a mohawk ' ",
		" u:ウ more-angular and with a tick for its top line ",
		" TT: middle> to the '4' char  う : Kata looks like the wa:ワ albeit with a mohawk ' ",
		" う:ウ ,  Compare:  wa:ワ cascading wa-ter fall,　um-'ca'y "},
	//
	// 2 of e:え:'エ'   2 times for e:え
	{"エ", "え", "e", "eエ", "え",
		" e:え:'エ' does have a vague, angular resemblance: eye see it as an, eye; may-bey, may-b-eh e ",
		" e:え ... see 'エ' as a ... an ... eye eh; may-bey, m'ay'-b-eh e   e:え:エ ",
		" TT: index> to the '5' char   e:え:エ ",
		" エ, eye see it as a ... an, eye ??  eh?:え:エ"},
	//
	{"エ", "え", "e", "eエ", "え",
		" e:え:'エ' does have a vague, angular resemblance: eye see it as an, eye; may-bey, may-b-eh e ",
		" e:え ... see 'エ' as a ... an ... eye eh; may-bey, m'ay'-b-eh e   e:え:エ ",
		" TT: index> to the '5' char   e:え:エ ",
		" エ, eye see it as a ... an, eye ??  eh?:え:エ"},
	//
	// 2 of o:お:オ
	{"オ", "お", "o", "oオ", "お",
		" o:お:オ , and オ does have a vague resemblance, albeit with less curves: お オ",
		" o:お , for the Kata オ ... think: someone is 'on-the-go' ... see the fl'o'w ",
		" TT: index--> to the '6' char     o:お:オ ",
		" お:オ, on-the-go, cloak trailing behind ... maybe? "},
	//
	{"オ", "お", "o", "oオ", "お",
		" o:お:オ , and オ does have a vague resemblance, albeit with less curves: お オ",
		" o:お , for the Kata オ ... think: someone is 'on-the-go' ... see the fl'o'w ",
		" TT: index--> to the '6' char     o:お:オ ",
		" お:オ, on-the-go, cloak trailing behind ... maybe? "},
	//
	// ka group: (ka-ga) ============================================================================================
	// 2 ka
	{"カ", "か", "ka", "kaカ", "か",
		" ka:か:カ ... is an easy one!  It simply looks like a 'K' ",
		" ... Kata is the same カ , albeit more-angular and with one-less line to draw than か ",
		" TT: index--> to the 'T' char   か ",
		" か:カ ... is an easy one!  It simply looks like a 'K'"},
	{"カ", "か", "ka", "kaカ", "か",
		" ka:か:カ ... is an easy one!  It simply looks like a 'K' ",
		" ... Kata is the same カ , albeit more-angular and with one-less line to draw than か ",
		" TT: index--> to the 'T' char   か ",
		" か:カ ... is an easy one!  It simply looks like a 'K'"},
	//
	// 2 of ki, ku, ke, ko
	{"キ", "き", "ki", "kiキ", "き",
		" ki:き:キ ... is an easy one!   キ has the same top as ki:き ... and they look like 'keys' ",
		" ki:き ... they both have the same top:  き キ",
		" TT: L-index> to the 'G' char,  Think: ki-of-G  き ,  Compare:  sa:さ-ki:き  さき ... saki ",
		"き:キ ... is an easy one!   キ has the same top as き ... and they look like 'keys' "},
	{"キ", "き", "ki", "kiキ", "き",
		" ki:き:キ ... is an easy one!   キ has the same top as ki:き ... and they look like 'keys' ",
		" ki:き ... they both have the same top:  き キ",
		" TT: L-index> to the 'G' char,  Think: ki-of-G  き ,  Compare:  sa:さ-ki:き  さき ... saki ",
		"き:キ ... is an easy one!   キ has the same top as き ... and they look like 'keys' "},
	// 2 ku
	{"ク", "く", "ku", "kuク", "く",
		" ku:く:ク ,  Kata: starting with one angle, they settled for this??  く:ク ",
		" ku:く:ク ,  Compare:  ta:タ  ke:ケ  ku:ク  クケタ,  it's kuku, kookoo I tell you! ",
		" TT: R-index<- to the 'H' char  く:ク ",
		"く:ク ,  Compare:  クケタ ta:タ  ke:ケ  ?:ク  ,  it's kookoo I tell you!"},
	{"ク", "く", "ku", "kuク", "く",
		" ku:く:ク ,  Kata: starting with one angle, they settled for this??  く:ク ",
		" ku:く:ク ,  Compare:  ta:タ  ke:ケ  ku:ク  クケタ,  it's kuku, kookoo I tell you! ",
		" TT: R-index<- to the 'H' char  く:ク ",
		"く:ク ,  Compare:  クケタ ta:タ  ke:ケ  ?:ク  ,  it's kookoo I tell you!"}, //
	// 2 ke
	{"ケ", "け", "ke", "keケ", "け",
		" ke:け:ケ  bits of it are there, just as many curves though ,  Compare to:  ku:ク  ta:タ ",
		" ke:け  ... looks enough like a Keg ...  Foam-ment THAT image in your brain ",
		" TT: pinky-> one-over to the ':*' chars   け:ケ ",
		"け:ケ  bits still there, as many curves though,  Compare:  ku:ク  ta:タ  クケタ"},
	{"ケ", "け", "ke", "keケ", "け",
		" ke:け:ケ  bits of it are there, just as many curves though ,  Compare to:  ku:ク  ta:タ ",
		" ke:け  ... looks enough like a Keg ...  Foam-ment THAT image in your brain ",
		" TT: pinky-> one-over to the ':*' chars   け:ケ ",
		"け:ケ  bits still there, as many curves though,  Compare:  ku:ク  ta:タ  クケタ"},
	// 2 ko   2 times for ko:こ:コ
	{"コ", "こ", "ko", "koコ", "こ",
		" ko:こ:コ ... it makes sense, 'cause angles:  ko:コ ,  Compare:  ni:に:ニ ",
		" ... see the two Koy fish?   'ko'oy fish? ",
		" TT: index <--- to the 'B' char,  ko way-down below  こ ",
		" こ:コ   TT: index <--- to the 'B' char    Compare:  ni:に:ニ"},
	{"コ", "こ", "ko", "koコ", "こ",
		" ko:こ:コ ... it makes sense, 'cause angles:  ko:コ ,  Compare:  ni:に:ニ ",
		" ... see the two Koy fish?   'ko'oy fish? ",
		" TT: index <--- to the 'B' char,  ko way-down below  こ ",
		" こ:コ   TT: index <--- to the 'B' char    Compare:  ni:に:ニ"},

	//
	// ka becomes ga group: -----------------------------------------------------------------------------------------
	// 2 ga
	{"ガ", "が", "ga", "gaガ", "が",
		" ga:ガ:が  same ガ albeit more angular with one-less line to draw than が",
		" ga:が is an easy one. ka--> ga,gi,gu,ge,go with a dakuten 濁点",
		" TT: index --> to the 'T' char, plus a dakuten 濁点 ",
		" ガ:が   TT: index --> to the 'T' char,  Kata has one-less line to draw"},
	{"ガ", "が", "ga", "gaガ", "が",
		" ga:ガ:が  same ガ albeit more angular with one-less line to draw than が",
		" ga:が is an easy one. ka--> ga,gi,gu,ge,go with a dakuten 濁点",
		" TT: index --> to the 'T' char, plus a dakuten 濁点 ",
		" ガ:が   TT: index --> to the 'T' char,  Kata has one-less line to draw"},
	// 2 gi
	{"ギ", "ぎ", "gi", "giギ", "ぎ",
		" gi:ぎ:ギ is an easy Kata, ギ has the same top as ki:き, and is NEVER from shi:し ",
		" ぎ:ギ is always the sound gi, and is Seldom ji ( that usually being じ:ji:ジ )",
		" TT: 'G' char, ぎ:ギ, compare to za:ざ from sa:さ",
		" It's sound is always from き ,and NEVER from し or ち  ka--> ga,?,gu,ge,go"},
	{"ギ", "ぎ", "gi", "giギ", "ぎ",
		" gi:ぎ:ギ is an easy Kata, ギ has the same top as ki:き, and is NEVER from shi:し ",
		" ぎ:ギ is always the sound gi, and is Seldom ji ( that usually being じ:ji:ジ )",
		" TT: 'G' char, ぎ:ギ, compare to za:ざ from sa:さ",
		" It's sound is always from き ,and NEVER from し or ち  ka--> ga,?,gu,ge,go"},
	//
	// 4 times for gu:ぐ:グ
	{"グ", "ぐ", "gu", "guグ", "ぐ",
		" gu:ぐ:グ Starting with one angle, they settled for this?  Compare:  ta:da:ダ, and ke:ge:ゲ",
		" gu:ぐ:グ  Compare:  da:ダ, ge:ゲ    ダグゲ　",
		" TT: R-index to 'H' char, plus dakuten 濁点     ka,ki,ku,ke,ko-->ga,gi,gu,ge,go",
		" ぐ:グ  TT: R-index to 'H' char, plus dakuten 濁点   Compare:  da:ダ, ge:ゲ  ダグゲ  "},
	{"グ", "ぐ", "gu", "guグ", "ぐ",
		" gu:ぐ:グ Starting with one angle, they settled for this?  Compare:  ta:da:ダ, and ke:ge:ゲ",
		" gu:ぐ:グ  Compare:  da:ダ, ge:ゲ    ダグゲ　",
		" TT: R-index to 'H' char, plus dakuten 濁点     ka,ki,ku,ke,ko-->ga,gi,gu,ge,go",
		" ぐ:グ  TT: R-index to 'H' char, plus dakuten 濁点   Compare:  da:ダ, ge:ゲ  ダグゲ  "},
	{"グ", "ぐ", "gu", "guグ", "ぐ",
		" gu:ぐ:グ Starting with one angle, they settled for this?  Compare:  ta:da:ダ, and ke:ge:ゲ",
		" gu:ぐ:グ  Compare:  da:ダ, ge:ゲ    ダグゲ　",
		" TT: R-index to 'H' char, plus dakuten 濁点     ka,ki,ku,ke,ko-->ga,gi,gu,ge,go",
		" ぐ:グ  TT: R-index to 'H' char, plus dakuten 濁点   Compare:  da:ダ, ge:ゲ  ダグゲ  "},
	{"グ", "ぐ", "gu", "guグ", "ぐ",
		" gu:ぐ:グ Starting with one angle, they settled for this?  Compare:  ta:da:ダ, and ke:ge:ゲ",
		" gu:ぐ:グ  Compare:  da:ダ, ge:ゲ    ダグゲ　",
		" TT: R-index to 'H' char, plus dakuten 濁点     ka,ki,ku,ke,ko-->ga,gi,gu,ge,go",
		" ぐ:グ  TT: R-index to 'H' char, plus dakuten 濁点   Compare:  da:ダ, ge:ゲ  ダグゲ  "},
	//
	// 4 times for ge:げ:ゲ   times for ge:げ:ゲ
	{"ゲ", "げ", "ge", "geゲ", "げ",
		" ge:げ:ゲ bits still there (as many curves though)  Compare  ku:gu:グ,  &  ta:za:ダ",
		" ge:げ Compare to ku:gu:グ, and ta:za:ダ   don't forget the dakuten 濁点",
		" TT: ':*' chars, 濁点    げ:ゲ  ダグゲ    ka,ki,ku,ke,ko-->ga,gi,gu,?,go  濁点",
		" げ:ゲ   TT: L-pinky> to ':*' chars   げ Compare to ku:gu:グ, and ta:da:ダ "},
	{"ゲ", "げ", "ge", "geゲ", "げ",
		" ge:げ:ゲ bits still there (as many curves though)  Compare  ku:gu:グ,  &  ta:za:ダ",
		" ge:げ Compare to ku:gu:グ, and ta:za:ダ   don't forget the dakuten 濁点",
		" TT: ':*' chars, 濁点    げ:ゲ  ダグゲ    ka,ki,ku,ke,ko-->ga,gi,gu,?,go  濁点",
		" げ:ゲ   TT: L-pinky> to ':*' chars   げ Compare to ku:gu:グ, and ta:da:ダ "},
	{"ゲ", "げ", "ge", "geゲ", "げ",
		" ge:げ:ゲ bits still there (as many curves though)  Compare  ku:gu:グ,  &  ta:za:ダ",
		" ge:げ Compare to ku:gu:グ, and ta:za:ダ   don't forget the dakuten 濁点",
		" TT: ':*' chars, 濁点    げ:ゲ  ダグゲ    ka,ki,ku,ke,ko-->ga,gi,gu,?,go  濁点",
		" げ:ゲ   TT: L-pinky> to ':*' chars   げ Compare to ku:gu:グ, and ta:da:ダ "},
	{"ゲ", "げ", "ge", "geゲ", "げ",
		" ge:げ:ゲ bits still there (as many curves though)  Compare  ku:gu:グ,  &  ta:za:ダ",
		" ge:げ Compare to ku:gu:グ, and ta:za:ダ   don't forget the dakuten 濁点",
		" TT: ':*' chars, 濁点    げ:ゲ  ダグゲ    ka,ki,ku,ke,ko-->ga,gi,gu,?,go  濁点",
		" げ:ゲ   TT: L-pinky> to ':*' chars   げ Compare to ku:gu:グ, and ta:da:ダ "},
	//
	// 3 go
	{"ゴ", "ご", "go", "goゴ", "ご",
		" go:ご:ゴ  it makes sense, 'cause angles' ",
		" go:ご:ゴ ",
		" TT: index <--- to the 'B' char    ご",
		" ご:ゴ  it makes sense, 'cause angles'   ka,ki,ku,ke,ko-->ga,gi,gu,ge,?"},
	{"ゴ", "ご", "go", "goゴ", "ご",
		" go:ご:ゴ  it makes sense, 'cause angles' ",
		" go:ご:ゴ ",
		" TT: index <--- to the 'B' char    ご",
		" ご:ゴ  it makes sense, 'cause angles'   ka,ki,ku,ke,ko-->ga,gi,gu,ge,?"},
	{"ゴ", "ご", "go", "goゴ", "ご",
		" go:ご:ゴ  it makes sense, 'cause angles' ",
		" go:ご:ゴ ",
		" TT: index <--- to the 'B' char    ご",
		" ご:ゴ  it makes sense, 'cause angles'   ka,ki,ku,ke,ko-->ga,gi,gu,ge,?"},
	//
	// ya, yu, yo's of ki:き ---------------------------------------------------------------------------
	//
	{"キャ", "きゃ", "kya", "kyaキャ", "きゃ",
		" kya:きゃ is an easy one, キャ has the same top, & the 'ya' is similar",
		" kya:きゃ キャ has the same top and the 'ya' is similar",
		" TT: 'G' char, then index <-- to the 7 char    きゃ,   Compare:  sa:さ ",
		" きゃ is an easy one, キャ has the same top, & the 'ya' is similar"},
	{"キュ", "きゅ", "kyu", "kyuキュ", "きゅ",
		" kyu:きゅ キュ has the same top",
		" kyu: ゅ:ュ",
		" TT: yu:ゅ index->, to the '8' char, yu looks like:  ユ are #1",
		" Key-ゅ   and:  ユ are #1     キュ has the same top as き "},
	{"キョ", "きょ", "kyo", "kyoキョ", "きょ",
		" kyo:きょ:キョ   キョ  has the same top",
		" kyo:キョ ",
		" TT: ょ:ョ middle to the '9' char, triple yo:ょ ヨ",
		" Key-ょ  キョ has the same top as き   hira:ょ is a yoyo , triple yo:ヨ"},
	//
	// ya, yu, yo's of gi:ぎ ---------------------------------------------------------------------------
	//
	{"ギャ", "ぎゃ", "gya", "gyaギャ", "ぎゃ",
		" gya  gi:ぎ:ギ is an easy Kata, ギ has the same top as ki:き, and is NEVER from shi:し",
		" gya:ギャ ",
		" TT: ya:ゃ index <-- to the 7 char",
		" ぎ:ギ is an easy Kata, ギ has the same top as ki:き   ka,ki,ku,ke,ko-->ga,?,gu,ge,go"},
	{"ギュ", "ぎゅ", "gyu", "gyuギュ", "ぎゅ",
		" gyu:ぎゅ:ギュ   ギ has same top as ki:き   ka,(ki),ku,ke,ko-->ga,(gi),gu,ge,go",
		" gyu:ぎゅ:ギュ ",
		" TT: yu:ゅ index->, to the '8' char, yu looks like:  ユ are #1",
		" ぎ:ギ is an easy Kata, ギ has the same top as ki:き    ka,ki,ku,ke,ko-->ga,?,gu,ge,go"},
	{"ギョ", "ぎょ", "gyo", "gyoギョ", "ぎょ",
		" gyo: gi:ぎ:ギ is an easy Kata, ギ has the same top as ki:き, and is NEVER from shi:し ",
		" gyo: ぎ:ギ is always the sound gi, and is Seldom ji ( that usually being じ:ji:ジ )",
		" TT: 'G' char, ぎ:ギ, then ょ:ョ:middle to the '9' char, triple yo:ょ ヨ      Compare: ざ",
		" It's sound is always from き ,and NEVER from し or ち   ka,ki,ku,ke,ko--> ga,?,gu,ge,go"},
	//
	// sa group: (sa-za,ji,zu,za,zo) ================================================================================
	// 2 of each: sa, shi, su, se ***
	{"サ", "さ", "sa", "saサ", "さ",
		" sa:さ:サ , if you 'se':せ そサ ,  Compare:  Hira se:せ  to  Kata sa:サ  せサ ",
		" ... , but it looks an awful-lot like Hira se:せ, I'd say   ... just 'Hir'-say ?? ",
		" TT: ring>v to the 'X' char  --  at least Kata 'sa' still goes to the left ... ",
		" さ:サ ,  Compare:  Hira:se:せ  to  Kata:?:サ  せサ se:? "},
	{"シ", "し", "shi", "shiシ", "し",
		" shi:し:シ  'she' sleeps & snores゛,  Compare: tsu:ツ & so:ソ　to the more-laid-back shi:シ ",
		" shi:し:シ  し looks like a sheep hook,  Compare: ツシ  tsu-shi ",
		" TT: on the 'D' char, シ 'she' is sleeping/snoring,  (no angles here, less curve though)",
		" し:シ  TT: on the 'D' char   Compare: tsu:ツ  & so:ソ　to the more-laid-back シ:し"},
	{"ス", "す", "su", "suス", "す",
		" su:す:ス ",
		" ス sue:す looks like she is running (and they were looking for angles)",
		" TT: left-index < to the 'R' char,  (sue is running ス)",
		" ス:す  she is running  TT: left-index < to the 'R' char"},
	{"セ", "せ", "se", "seセ", "せ",
		" se:せ:セ  ... セ is just a bit more angular, as is the way with most Katakana ",
		" se:せ looks like a face saying something ... 'se'ing something ",
		" TT: pinky to the 'P' char",
		" せ:セ  ... セ is just a bit more angular, as is the way with most Katakana"},
	// second set ::
	{"サ", "さ", "sa", "saサ", "さ",
		" sa:さ:サ , if you 'se':せ そサ ,  Compare:  Hira se:せ  to  Kata sa:サ  せサ ",
		" ... , but it looks an awful-lot like Hira se:せ, I'd say   ... just 'Hir'-say ?? ",
		" TT: ring>v to the 'X' char  --  at least Kata 'sa' still goes to the left ... ",
		" さ:サ ,  Compare:  Hira:se:せ  to  Kata:?:サ  せサ se:? "},
	{"シ", "し", "shi", "shiシ", "し",
		" shi:し:シ  'she' sleeps & snores゛,  Compare: tsu:ツ & so:ソ　to the more-laid-back shi:シ ",
		" shi:し:シ  し looks like a sheep hook,  Compare: ツシ  tsu-shi ",
		" TT: on the 'D' char, シ 'she' is sleeping/snoring,  (no angles here, less curve though)",
		" し:シ  TT: on the 'D' char   Compare: tsu:ツ  & so:ソ　to the more-laid-back シ:し"},
	{"ス", "す", "su", "suス", "す",
		" su:す:ス ",
		" ス sue:す looks like she is running (and they were looking for angles)",
		" TT: left-index < to the 'R' char,  (sue is running ス)",
		" ス:す  she is running  TT: left-index < to the 'R' char"},
	{"セ", "せ", "se", "seセ", "せ",
		" se:せ:セ  ... セ is just a bit more angular, as is the way with most Katakana ",
		" se:せ looks like a face saying something ... 'se'ing something ",
		" TT: pinky to the 'P' char",
		" せ:セ  ... セ is just a bit more angular, as is the way with most Katakana"},
	//
	//  5 times so:そ:ソ
	// Seriously?  so:ソ vs nh:ン  ... I guess nh got nh-ocked-down by an upper-cut to the chin
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	{"ソ", "そ", "so", "soソ", "そ",
		" so:そ:ソ  starting with all angles -- I guess they `had to `backtrack? ",
		" so:そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick ",
		" TT: index<-- to the 'C' char,  so:ソ Looks like: し:シ  & no:ノ but MOSTLY like:  n:ん:ン ",
		" そ:ソ ,  Compare:  n:ん:ン which lays-down more, and has a more-laid-down back-tick "},
	//
	// sa becomes za, ji, zu, ze, zo --------------------------------------------------------------------------------
	//
	{"ザ", "ざ", "za", "zaザ", "ざ",
		" sa-->za:ざ ",
		" sa-->za   za:za:ザ ",
		" TT: down on the 'X' char for sa:za",
		" ?:ざ:ザ "},
	{"ジ", "じ", "ji", "jiジ", "じ",
		" ji:ジ is from shi:し & Seldom is it fr chi:ち ,it's the sound ji, NEVER gi (that being ぎ:gi:ギ)",
		" ji, the sound, VERY RARELY is from chi:ち:ヂ ,but is NEVER the sound gi (that being ぎ:gi:ギ)",
		" TT: 'D' char, remember, the sound:ji is nearly-always from shi:し with a dakuten 濁点 じ:ジ",
		" ジ:じ the sound, VERY Seldom from ち, it's sound:gee:jeep, NEVER gi:geek(that being ぎ:gi:ギ)"},
	// zu has two KeyR values **** when prompting with naked Romaji **** 1:"zu", and 2::づ
	{"ズ", "ず", "zu", "zuズ", "ず",
		" zu:ず:ズ:づ:ヅ: , is either ず:ズ or づ:ヅ , as they are both the same sound",
		" zu: 'Sue' ズ is running with her hair flowing behind her (from su:す) ",
		"  TT: L-index< to the 'R' char, same sound: a big wave つ  or a  snake ず at the zoo",
		" ?:ず:ズ づ:ヅ  same sound   TT: left-index< to the 'R' char, dakuten 濁点 "},
	{"ゼ", "ぜ", "ze", "zeゼ", "ぜ",
		" sa-->za   se-->ze ",
		" ze:ゼ:ぜ",
		" TT: pinky to the 'P' char   ze:ゼ:ぜ",
		" ?:ゼ:ぜ   sa-->za  se:? "},
	// 3 zo
	{"ゾ", "ぞ", "zo", "zoゾ", "ぞ",
		" zo:ぞ:ゾ  it's soo big!   Compare: n:ん:ン which lays-down more",
		" zo:ぞ:ゾ  long hair and a big one,  Compare:  し:シ  &  no:ノ,  or  n:ん:ン ",
		" TT: left-index <-- to the C char, plus a dakuten 濁点 , a big one!",
		" ?:ぞ:ゾ  TT: left-index <-- to the C char, not no:ノ | n:ん:ン which lays-down more"},
	{"ゾ", "ぞ", "zo", "zoゾ", "ぞ",
		" zo:ぞ:ゾ  it's soo big!   Compare: n:ん:ン which lays-down more",
		" zo:ぞ:ゾ  long hair and a big one,  Compare:  し:シ  &  no:ノ,  or  n:ん:ン ",
		" TT: left-index <-- to the C char, plus a dakuten 濁点 , a big one!",
		" ?:ぞ:ゾ  TT: left-index <-- to the C char, not no:ノ | n:ん:ン which lays-down more"},
	{"ゾ", "ぞ", "zo", "zoゾ", "ぞ",
		" zo:ぞ:ゾ  it's soo big!   Compare: n:ん:ン which lays-down more",
		" zo:ぞ:ゾ  long hair and a big one,  Compare:  し:シ  &  no:ノ,  or  n:ん:ン ",
		" TT: left-index <-- to the C char, plus a dakuten 濁点 , a big one!",
		" ?:ぞ:ゾ  TT: left-index <-- to the C char, not no:ノ | n:ん:ン which lays-down more"},
	//
	// ya, yu, yo's of shi:し:シ ------------------------------------------------------------------------
	//
	{"シャ", "しゃ", "sha", "shaシャ", "しゃ",
		" sha",
		" sha",
		" sha",
		" sha"},
	{"シュ", "しゅ", "shu", "shuシュ", "しゅ",
		" shu",
		" shu",
		" shu",
		" shu"},
	{"ショ", "しょ", "sho", "shoショ", "しょ",
		" sho",
		" sho",
		" sho",
		" sho"},
	//
	// ya, yu, yo's of ji:じ:ジ -------------------------------------------------------------------------
	//
	{"ジャ", "じゃ", "ja", "jaジャ", "じゃ",
		" ja:じゃ:ジャ is nearly-always from shi:し and really never from chi:ち , ヂャ is obsolete",
		" ja:ジャ:じゃ , obsolete:ヂャ is an obsolete construct for ja",
		" ja:",
		" ja:"},
	{"ジュ", "じゅ", "ju", "juジュ", "じゅ",
		" ju:ジュ:じゅ is nearly-always from shi:し and really never from chi:ち",
		" ju:じゅ:ジュ , obsolete:ヂュ is an obsolete construct for ju",
		" ju: ",
		" ju: "},
	{"ジョ", "じょ", "jo", "joジョ", "じょ",
		" jo:じょ:ジョ is nearly-always from shi:し and really never from chi:ち",
		" jo:ジョ:じょ , obsolete:ヂョ is an obsolete construct for jo",
		" jo: ",
		" jo: "},
	//
	// ta group: (ta->da,ji,zu,de,do) ================================================================================
	//
	// 2 of each ta,chi,tsu,te,to
	{"タ", "た", "ta", "taタ", "た",
		" ta:た:タタタタ  ta-da!... it's a ku:くクタ with a drool ... and that's くool I guess ",
		" ta:た:タ ,  Compare:  ku:ク  &  ke:ケ ",
		" TT: pinky< to the 'Q' char ",
		" top of ta:タ looks like た,   more than ku:ク looks like く  "},
	{"チ", "ち", "chi", "chiチ", "ち",
		" chi:ち:チ ,   ち チ ",
		" ...  chi:ち:チ ,  Compare:  chi:チ  te:テ ",
		" TT: pinky on the 'A' char ",
		" Kata bares 'some' resemblance to ち "},
	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},
	{"テ", "て", "te", "teテ", "て",
		" te:て:テ ",
		" te:て:テ ,  Compare:  chi:チ テ:て ",
		" TT: ring< to the 'W' char, te:テ:て  went the wrong way, and gained a flat hat ",
		" ?:て:テ ,  Compare:  chi:チ テ:て "},
	{"ト", "と", "to", "toト", "と",
		" to:と:ト   Kata 'toe' is flipped-out. Kicked in the balls. on its head: と -> ト ",
		" Katakana to:と is flipped-out. Kicked in the balls, On its head ",
		" TT: ring on the 'S' char, Kata toe is flipped-out. Kicked on its head: と -> ト ",
		" Kata ? is flipped-out. Kicked in the balls. On its head: と --> ト "},
	// second set:
	{"タ", "た", "ta", "taタ", "た",
		" ta:た:タタタタ  ta-da!... it's a ku:くクタ with a drool ... and that's くool I guess ",
		" ta:た:タ ,  Compare:  ku:ク  &  ke:ケ ",
		" TT: pinky< to the 'Q' char ",
		" top of ta:タ looks like た,   more than ku:ク looks like く  "},
	{"チ", "ち", "chi", "chiチ", "ち",
		" chi:ち:チ ,   ち チ ",
		" ...  chi:ち:チ ,  Compare:  chi:チ  te:テ ",
		" TT: pinky on the 'A' char ",
		" Kata bares 'some' resemblance to ち "},
	{"ツ", "つ", "tsu", "tsuツ", "つ",
		" tsu:つ:ツ  see water crashing on the she shore",
		" tsu",
		" TT: left-pinky on 'Z' char",
		" ?:つ:ツ see water crashing on the she shore  TT: left-pinky on 'Z' char"},
	{"テ", "て", "te", "teテ", "て",
		" te:て:テ ",
		" te:て:テ ,  Compare:  chi:チ テ:て ",
		" TT: ring< to the 'W' char, te:テ:て  went the wrong way, and gained a flat hat ",
		" ?:て:テ ,  Compare:  chi:チ テ:て "},
	{"ト", "と", "to", "toト", "と",
		" to:と:ト   Kata 'toe' is flipped-out. Kicked in the balls. on its head: と -> ト ",
		" Katakana to:と is flipped-out. Kicked in the balls, On its head ",
		" TT: ring on the 'S' char, Kata toe is flipped-out. Kicked on its head: と -> ト ",
		" Kata ? is flipped-out. Kicked in the balls. On its head: と --> ト "},
	//
	// ta becomes da, ji, zu, de, do --------------------------------------------------------------------------------
	//
	// 2 da
	{"ダ", "だ", "da", "daダ", "だ",
		" ta-->da  だ:ダ ",
		" da",
		" TT: ",
		" ta-->? "},
	{"ダ", "だ", "da", "daダ", "だ",
		" ta-->da  だ:ダ ",
		" da",
		" TT: ",
		" ta-->? "},
	// 2 zu
	// : zu has 2 KeyR values **** when prompting with naked Romaji **** 1:"zu", and 2::づ
	{"ヅ", "づ", "zu", "zuヅ", "づ",
		" zu:づ:ヅ ず:ズ , is either ず:ズ or づ:ヅ , as they are both the same sound ",
		" zu: for the Kataす think 'Sue' ズ is running with her hair flowing behind her",
		" TT: L-pinky>v to the 'Z' char, plus dakuten 濁点 ",
		" ?:づ:ヅ ず:ズ  that big wave つ sounds the same, TT: L-pinky>v to the 'Z' char"},
	// zu has 2 KeyR values **** when prompting with naked Romaji **** 1:"zu", and 2::づ
	{"ヅ", "づ", "zu", "zuヅ", "づ",
		" zu:づ:ヅ ず:ズ , is either ず:ズ or づ:ヅ , as they are both the same sound ",
		" zu: for the Kataす think 'Sue' ズ is running with her hair flowing behind her",
		" TT: L-pinky>v to the 'Z' char, plus dakuten 濁点 ",
		" ?:づ:ヅ ず:ズ  that big wave つ sounds the same, TT: L-pinky>v to the 'Z' char"},
	// 2 de
	{"デ", "で", "de", "deデ", "で",
		" de:で:デ ",
		" de",
		" TT: de",
		" ?:で:デ "},
	{"デ", "で", "de", "deデ", "で",
		" de:で:デ ",
		" de",
		" TT: de",
		" ?:で:デ "},
	// 2 do
	{"ド", "ど", "do", "doド", "ど",
		" do:ド:ど   ta-->da  to --> do    plus a dakuten 濁点",
		" do:ど:ド ",
		" TT: left-ring on the 'S' char, plus a dakuten 濁点 ",
		" ?:ど:ド  TT: left-ring on the 'S' char, plus a dakuten 濁点   ta-->da  to-->? "},
	{"ド", "ど", "do", "doド", "ど",
		" do:ド:ど   ta-->da  to --> do    plus a dakuten 濁点",
		" do:ど:ド ",
		" TT: left-ring on the 'S' char, plus a dakuten 濁点 ",
		" ?:ど:ド  TT: left-ring on the 'S' char, plus a dakuten 濁点   ta-->da  to-->? "},
	//
	// ya, yu, yo's of chi:ち:チ ------------------------------------------------------------------------
	//
	{"チャ", "ちゃ", "cha", "chaチャ", "ちゃ",
		" cha",
		" cha",
		" cha",
		" cha"},
	{"チュ", "ちゅ", "chu", "chuチュ", "ちゅ",
		" chu",
		" chu",
		" chu",
		" chu"},
	{"チョ", "ちょ", "cho", "choチョ", "ちょ",
		" cho",
		" cho",
		" cho",
		" cho"},
	//
	// na group: (always a naked group) =============================================================================
	// 3 na
	{"ナ", "な", "na", "naナ", "な",
		" na:な:ナ  Kata ナ is just like the left side of the Hira な -- な:ナ ",
		" na:な:ナ , Compare:  na:ナ  me:メ  nu:ヌ  ( め ぬ )",
		" TT: index< to the 'U' char,  ナ is very simple ... na-t complex at-all :: な ",
		" な:ナ  TT: index< to the 'U' char, Hiragana t-ies a knot, see the two chars thar "},
	{"ナ", "な", "na", "naナ", "な",
		" na:な:ナ  Kata ナ is just like the left side of the Hira な -- な:ナ ",
		" na:な:ナ , Compare:  na:ナ  me:メ  nu:ヌ  ( め ぬ )",
		" TT: index< to the 'U' char,  ナ is very simple ... na-t complex at-all :: な ",
		" な:ナ  TT: index< to the 'U' char, Hiragana t-ies a knot, see the two chars thar "},
	{"ナ", "な", "na", "naナ", "な",
		" na:な:ナ  Kata ナ is just like the left side of the Hira な -- な:ナ ",
		" na:な:ナ , Compare:  na:ナ  me:メ  nu:ヌ  ( め ぬ )",
		" TT: index< to the 'U' char,  ナ is very simple ... na-t complex at-all :: な ",
		" な:ナ  TT: index< to the 'U' char, Hiragana t-ies a knot, see the two chars thar "},
	// 1 ni
	{"ニ", "に", "ni", "niニ", "に",
		" ni:に:ニ  I can see a knee-cap in the Hiragana ",
		" ni:に:ニ  ",
		" TT: middle< to the 'I' char ",
		" ?:に:ニ  I can see a knee-cap in the Hiragana "},
	// 2 of nu,ne,no
	{"ヌ", "ぬ", "nu", "nuヌ", "ぬ",
		" nu:ぬ:ヌ   Compare:  me:メ  &  na:ナ ",
		" nu flew ヌ -- till it hit a ceiling ",
		" TT: R-ring<--- to the '1' char, at least two lines cross, nu flew ヌ -- hit a ceiling ",
		" ?-flew ヌ -- till it hit a ceiling "},
	{"ネ", "ね", "ne", "neネ", "ね",
		" ne:ね:ネ  Kata looks like a hoe that got nailed ネ ",
		" something got nailed-down by that spike at the left ",
		" TT: R-ring<v to the ',<' chars  ...  Yea, to me it is a hoe:ほ that got nailed ネ ",
		" ?:ね:ネ  Kata looks like a hoe that got nailed ネ  TT: R-ring<v to the ',<' chars"},
	{"ノ", "の", "no", "noノ", "の",
		" no:の:ノ   it looks like a 'no' symbol ",
		" no:の:ノ  and the Kata retains the slash ",
		" TT: right-middle on 'K' char",
		" ?:の:ノ  TT: right-middle on 'K' char   ?-thank-you "},
	// second set:
	{"ヌ", "ぬ", "nu", "nuヌ", "ぬ",
		" nu:ぬ:ヌ   Compare:  me:メ  &  na:ナ ",
		" nu flew ヌ -- till it hit a ceiling ",
		" TT: R-ring<--- to the '1' char, at least two lines cross, nu flew ヌ -- hit a ceiling ",
		" ?-flew ヌ -- till it hit a ceiling "},
	{"ネ", "ね", "ne", "neネ", "ね",
		" ne:ね:ネ  Kata looks like a hoe that got nailed ネ ",
		" something got nailed-down by that spike at the left ",
		" TT: R-ring<v to the ',<' chars  ...  Yea, to me it is a hoe:ほ that got nailed ネ ",
		" ?:ね:ネ  Kata looks like a hoe that got nailed ネ  TT: R-ring<v to the ',<' chars"},
	{"ノ", "の", "no", "noノ", "の",
		" no:の:ノ   it looks like a 'no' symbol ",
		" no:の:ノ  and the Kata retains the slash ",
		" TT: right-middle on 'K' char",
		" ?:の:ノ  TT: right-middle on 'K' char   ?-thank-you "},
	//
	// ya, yu, yo's of ni:に:ニ -------------------------------------------------------------------------
	//
	{"ニャ", "にゃ", "nya", "nyaニャ", "にゃ",
		" nya",
		" nya",
		" nya",
		" nya"},
	{"ニュ", "にゅ", "nyu", "nyuニュ", "にゅ",
		" nyu",
		" nyu",
		" nyu",
		" nyu"},
	{"ニョ", "にょ", "nyo", "nyoニョ", "にょ",
		" nyo",
		" nyo",
		" nyo",
		" nyo"},
	//
	// ha group: (ha-fu ba:pa) ha:hi:fu:he:ho =======================================================================
	// 2 ha
	{"ハ", "は", "ha", "haハ", "は",
		" ha:ハ:は:ha  looks a bit like the letter H, and a ハ ha-haystack ハ ",
		" ha: ハ ha-haystack ハ ",
		" TT: left-index on it's 'F' char",
		" ハ:は   looks a bit like the letter    TT: left-index on it's 'F' char "},
	{"ハ", "は", "ha", "haハ", "は",
		" ha:ハ:は:ha  looks a bit like the letter H, and a ハ ha-haystack ハ ",
		" ha: ハ ha-haystack ハ ",
		" TT: left-index on it's 'F' char",
		" ハ:は   looks a bit like the letter    TT: left-index on it's 'F' char "},
	// 1 hi
	{"ヒ", "ひ", "hi", "hiヒ", "ひ",
		" hi:ひ:ヒ  a smiling mouth doing a hee-hee hi-hi",
		" hi, pronounced hee ",
		" TT: left-index > to the 'V' char",
		" ?:ひ:ヒ   '?'-man   TT: left-index > to the 'V' char"},
	// 3 fu
	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},
	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},
	{"フ", "ふ", "fu", "fuフ", "ふ",
		" fu:ふ:フ  ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" fu: think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" ふ:フ  TT: left-ring to the '2' char,  it is the big mountain in Japan "},
	// 1 he
	{"ヘ", "へ", "he", "heヘ", "へ",
		" he:ヘ:へ  Hira and Kata are pretty-much the same, both hay:he stacks",
		" he",
		" TT: left-pinky way-up to the '^' char",
		" ヘ:へ   TT: left-pinky way-up to the '^' char, clearly stacks of feed"},
	// 2 ho
	{"ホ", "ほ", "ho", "hoホ", "ほ",
		" ho",
		" ho",
		" ho",
		" ho"},
	{"ホ", "ほ", "ho", "hoホ", "ほ",
		" ho",
		" ho",
		" ho",
		" ho"},
	//
	// ba, bi, bu, be, bo -------------------------------------------------------------------------------------------
	// 2 ba
	{"バ", "ば", "ba", "baバ", "ば",
		" ba",
		" ba",
		" ba",
		" ha-->?"},
	{"バ", "ば", "ba", "baバ", "ば",
		" ba",
		" ba",
		" ba",
		" ha-->?"},
	// 1 bi
	{"ビ", "び", "bi", "biビ", "び",
		" bi",
		" bi",
		" bi",
		" bi"},
	// 3 bu
	{"ブ", "ぶ", "bu", "buブ", "ぶ",
		" bu",
		" bu",
		" bu",
		" bu"},
	{"ブ", "ぶ", "bu", "buブ", "ぶ",
		" bu",
		" bu",
		" bu",
		" bu"},
	{"ブ", "ぶ", "bu", "buブ", "ぶ",
		" bu",
		" bu",
		" bu",
		" bu"},
	// 1 be
	{"ベ", "べ", "be", "beベ", "べ",
		" be:ベ:べ  same same, , clearly stacks of feed, hay:he stacks, ",
		" be:  he-->be-->pe , dakuten 濁点, handakuten゜半濁点",
		" TT: left-pinky way-up to the '^' char, plus dakuten 濁点",
		" TT: left-pinky way-up to the '^' char, plus dakuten 濁点   stack of feed, "},
	// 2 bo
	{"ボ", "ぼ", "bo", "boボ", "ぼ",
		" bo:ボ:ぼ  looks like a hoe in a dress, ho-->bo-->po  dakuten, handakuten゜半濁点",
		" bo",
		" TT: right-ring-way-up to the '-' char, plus dakuten 濁点",
		" ボ:ぼ  TT: right-ring-way-up to the '-' char, plus dakuten 濁点"},
	{"ボ", "ぼ", "bo", "boボ", "ぼ",
		" bo:ボ:ぼ  looks like a hoe in a dress, ho-->bo-->po  dakuten, handakuten゜半濁点",
		" bo",
		" TT: right-ring-way-up to the '-' char, plus dakuten 濁点",
		" ボ:ぼ  TT: right-ring-way-up to the '-' char, plus dakuten 濁点"},
	//
	// pa, pi, pu, pe, po -------------------------------------------------------------------------------------------
	// 2 of each :: pa, pi, pu, pe, po
	{"パ", "ぱ", "pa", "paパ", "ぱ",
		" pa",
		" pa",
		" pa",
		" pa"},
	{"ピ", "ぴ", "pi", "piピ", "ぴ",
		" pi",
		" pi",
		" pi",
		" pi"},
	{"プ", "ぷ", "pu", "puプ", "ぷ",
		" pu:プ:ぷ   ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" pu:fu:  think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" プ:ぷ   TT: left-ring to the '2' char,  it is the big mountain in Japan"},
	{"ペ", "ぺ", "pe", "peペ", "ぺ",
		" pe:ペ:ぺ  same same, , clearly stacks of feed, hay:he stacks, handakuten゜半濁点",
		" pe:  he-->be-->pe , dakuten 濁点, handakuten゜半濁点",
		" TT: left-pinky way-up to the '^' char, plus handakuten゜半濁点",
		" ペ:ぺ   TT: left-pinky way-up to the '^' char, stack of feed, handakuten゜半濁点"},
	{"ポ", "ぽ", "po", "poポ", "ぽ",
		" po",
		" po",
		" po",
		" po"},
	// second set:
	{"パ", "ぱ", "pa", "paパ", "ぱ",
		" pa",
		" pa",
		" pa",
		" pa"},
	{"ピ", "ぴ", "pi", "piピ", "ぴ",
		" pi",
		" pi",
		" pi",
		" pi"},
	{"プ", "ぷ", "pu", "puプ", "ぷ",
		" pu:プ:ぷ   ふじ　Mount Fuji 富士山  富:Fu: wealth, abundant  士:Ji: gentleman, samurai, warrior",
		" pu:fu:  think Mt Fuji 'fu'ji,  fu or, alternatively, hu ",
		" TT: left-ring to the '2' char",
		" プ:ぷ   TT: left-ring to the '2' char,  it is the big mountain in Japan"},
	{"ペ", "ぺ", "pe", "peペ", "ぺ",
		" pe:ペ:ぺ  same same, , clearly stacks of feed, hay:he stacks, handakuten゜半濁点",
		" pe:  he-->be-->pe , dakuten 濁点, handakuten゜半濁点",
		" TT: left-pinky way-up to the '^' char, plus handakuten゜半濁点",
		" ペ:ぺ   TT: left-pinky way-up to the '^' char, stack of feed, handakuten゜半濁点"},
	{"ポ", "ぽ", "po", "poポ", "ぽ",
		" po",
		" po",
		" po",
		" po"},
	//
	// ya, yu, yo's of hi:ひ:ヒ -------------------------------------------------------------------------
	//
	{"ヒャ", "ひゃ", "hya", "hyaヒャ", "ひゃ",
		" hya",
		" hya",
		" hya",
		" hya"},
	{"ヒュ", "ひゅ", "hyu", "hyuヒュ", "ひゅ",
		" hyu",
		" hyu",
		" hyu",
		" hyu"},
	{"ヒョ", "ひょ", "hyo", "hyoヒョ", "ひょ",
		" hyo",
		" hyo",
		" hyo",
		" hyo"},
	//
	// ya, yu, yo's of bi:び:ビ -------------------------------------------------------------------------
	//
	{"ビャ", "びゃ", "bya", "byaビャ", "びゃ",
		" bya",
		" bya",
		" bya",
		" bya"},
	{"ビュ", "びゅ", "byu", "byuビュ", "びゅ",
		" byu",
		" byu",
		" byu",
		" byu"},
	{"ビョ", "びょ", "byo", "byoビョ", "びょ",
		" byo",
		" byo",
		" byo",
		" byo"},
	//
	// ya, yu, yo's of pi:ぴ:ピ -------------------------------------------------------------------------
	//
	{"ピャ", "ぴゃ", "pya", "pyaピャ", "ぴゃ",
		" pya",
		" pya",
		" pya",
		" pya"},
	{"ピュ", "ぴゅ", "pyu", "pyuピュ", "ぴゅ",
		" pyu",
		" pyu",
		" pyu",
		" pyu"},
	{"ピョ", "ぴょ", "pyo", "pyoピョ", "ぴょ",
		" pyo",
		" pyo",
		" pyo",
		" pyo"},
	//
	// ma group: ====================================================================================================
	// 2 of each ::
	{"マ", "ま", "ma", "maマ", "ま",
		" ma",
		" ma",
		" ma",
		" ma"},
	{"ミ", "み", "mi", "miミ", "み",
		" mi",
		" mi",
		" mi",
		" mi"},
	{"ム", "む", "mu", "muム", "む",
		" mu:ム:む  somehow, it does look like a cow",
		" mu",
		" TT: right-pinky way-over to the '}]' chars",
		" ム:む   TT: right-pinky way-over to the '}]' chars"},
	{"メ", "め", "me", "meメ", "め",
		" me",
		" me",
		" me",
		" me"},
	{"モ", "も", "mo", "moモ", "も",
		" mo:モ:も ",
		" mo",
		" TT: right-middle<v to the 'M' char",
		" モ:も   TT: right-middle<v to the 'M' char,  m is for ?"},
	// second set:
	{"マ", "ま", "ma", "maマ", "ま",
		" ma",
		" ma",
		" ma",
		" ma"},
	{"ミ", "み", "mi", "miミ", "み",
		" mi",
		" mi",
		" mi",
		" mi"},
	{"ム", "む", "mu", "muム", "む",
		" mu:ム:む  somehow, it does look like a cow",
		" mu",
		" TT: right-pinky way-over to the '}]' chars",
		" ム:む   TT: right-pinky way-over to the '}]' chars"},
	{"メ", "め", "me", "meメ", "め",
		" me",
		" me",
		" me",
		" me"},
	// 2 more mo's
	{"モ", "も", "mo", "moモ", "も",
		" mo:モ:も ",
		" mo",
		" TT: right-middle<v to the 'M' char",
		" モ:も   TT: right-middle<v to the 'M' char,  m is for ?"},
	{"モ", "も", "mo", "moモ", "も",
		" mo:モ:も ",
		" mo",
		" TT: right-middle<v to the 'M' char",
		" モ:も   TT: right-middle<v to the 'M' char,  m is for ?"},
	//
	// ya, yu, yo's of mi:み:ミ -------------------------------------------------------------------------
	//
	{"ミャ", "みゃ", "mya", "myaミャ", "みゃ",
		" mya",
		" mya",
		" mya",
		" mya"},
	{"ミュ", "みゅ", "myu", "myuミュ", "みゅ",
		" myu",
		" myu",
		" myu",
		" myu"},
	{"ミョ", "みょ", "myo", "myoミョ", "みょ",
		" myo",
		" myo",
		" myo",
		" myo"},
	//
	// "group" ya yu yo =============================================================================================
	//
	{"ヤ", "や", "ya", "yaヤ", "や",
		" ya",
		" ya",
		" ya",
		" ya"},
	{"ユ", "ゆ", "yu", "yuユ", "ゆ",
		" yu",
		" yu",
		" yu",
		" yu"},
	{"ヨ", "よ", "yo", "yoヨ", "よ",
		" yo",
		" yo",
		" yo",
		" yo"},
	//
	// ra group: (pronounced more like 'la') ========================================================================
	// 4 ra
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	{"ラ", "ら", "ra", "raラ", "ら",
		" ra:ら:ラ    Compare:  hu:フ u:ウ  ラ:ら:ra:la",
		" ra",
		" ra",
		" Compare:  hu:フ u:ウ  ラ:ら:? "},
	// 2 ri
	{"リ", "り", "ri", "riリ", "り",
		" ri:リ:り  actually, very very similar, actually!",
		" ri",
		" TT: left-ring-finger on it's 'L' char",
		" リ:り very similar   TT: left-ring-finger on it's 'L' char"},
	{"リ", "り", "ri", "riリ", "り",
		" ri:リ:り  actually, very very similar, actually!",
		" ri",
		" TT: left-ring-finger on it's 'L' char",
		" リ:り very similar   TT: left-ring-finger on it's 'L' char"},
	// 4 ru
	{"ル", "る", "ru", "ruル", "る",
		" ru",
		" ru",
		" ru",
		" ru"},
	{"ル", "る", "ru", "ruル", "る",
		" ru",
		" ru",
		" ru",
		" ru"},
	{"ル", "る", "ru", "ruル", "る",
		" ru",
		" ru",
		" ru",
		" ru"},
	{"ル", "る", "ru", "ruル", "る",
		" ru",
		" ru",
		" ru",
		" ru"},
	// 3 re
	{"レ", "れ", "re", "reレ", "れ",
		" re:レ:れ  laying on the little finger",
		" re:レ:れ  the れ looks like someone getting blown, laid ",
		" TT: left-pinky on it's ';' char",
		" レ:れ   TT: left-pinky on it's ';' char"},
	{"レ", "れ", "re", "reレ", "れ",
		" re:レ:れ  laying on the little finger",
		" re:レ:れ  the れ looks like someone getting blown, laid ",
		" TT: left-pinky on it's ';' char",
		" レ:れ   TT: left-pinky on it's ';' char"},
	{"レ", "れ", "re", "reレ", "れ",
		" re:レ:れ  laying on the little finger",
		" re:レ:れ  the れ looks like someone getting blown, laid ",
		" TT: left-pinky on it's ';' char",
		" レ:れ   TT: left-pinky on it's ';' char"},
	// 2 ro
	{"ロ", "ろ", "ro", "roロ", "ろ",
		" ro",
		" ro",
		" ro",
		" ro"},
	{"ロ", "ろ", "ro", "roロ", "ろ",
		" ro",
		" ro",
		" ro",
		" ro"},
	//
	// ya, yu, yo's of ri:り:リ ---------------------------------------------------------------------------
	//
	{"リャ", "りゃ", "rya", "ryaリャ", "りゃ",
		" rya",
		" rya",
		" rya",
		" rya"},
	{"リュ", "りゅ", "ryu", "ryuリュ", "りゅ",
		" ryu",
		" ryu",
		" ryu",
		" ryu"},
	{"リョ", "りょ", "ryo", "ryoリョ", "りょ",
		" ryo",
		" ryo",
		" ryo",
		" ryo"},
	//
	// wa and wo ====================================================================================================
	// 2 of each ::
	{"ワ", "わ", "wa", "waワ", "わ",
		" wa:ワ:わ  Water-fall, pissing in the wind (making わしこ) ",
		" wa",
		" TT: right-ring to the '0' char",
		" ワ:わ  aqua-fall   TT: right-ring to the '0' char"},
	{"ヲ", "を", "wo", "woヲ", "を",
		" wo:ヲ:を   Compare: fu:フ　wa:ワ　u:ウ　a:ア　te:テ:て　 ",
		" wo:ヲ, at least it looks something like wa:ワ, though shifted",
		" TT: right-ring up to the '0' char (shifted)",
		" ヲ:を   Compare: wa:ワ   TT: right-ring up to the '0' char (shifted)"},
	// second set:
	{"ワ", "わ", "wa", "waワ", "わ",
		" wa:ワ:わ  Water-fall, pissing in the wind (making わしこ) ",
		" wa",
		" TT: right-ring to the '0' char",
		" ワ:わ  aqua-fall   TT: right-ring to the '0' char"},
	{"ヲ", "を", "wo", "woヲ", "を",
		" wo:ヲ:を   Compare: fu:フ　wa:ワ　u:ウ　a:ア　te:テ:て　 ",
		" wo:ヲ, at least it looks something like wa:ワ, though shifted",
		" TT: right-ring up to the '0' char (shifted)",
		" ヲ:を   Compare: wa:ワ   TT: right-ring up to the '0' char (shifted)"},
	//
	// n ============================================================================================================
	// 2 n ::
	{"ン", "ん", "n", "nン", "ん",
		" n:ン:ん  looks like a cursive n, and sounds like it too",
		" n",
		" TT: index to the 'Y' char",
		" ン:ん   TT: index to the 'Y' char, sounds the way it looks"},
	{"ン", "ん", "n", "nン", "ん",
		" n:ン:ん  looks like a cursive n, and sounds like it too",
		" n",
		" TT: index to the 'Y' char",
		" ン:ん   TT: index to the 'Y' char, sounds the way it looks"},
}

//const aCard = charSetStruct{} // did not work

// The structure of a single 'card' (aCard.) from fileOfCards
type charSetStruct struct {
	KeyK  string
	KeyH  string
	KeyR  string
	KeyRK string

	// was: Value string
	Keyh string // New name for the old name (above)

	Hint1h    string
	Hint2k    string
	Hint3TT   string
	HintSansR string
}

/*
 Above, we instantiate a series of struct objects as a slice of instances of the charSetStruct type
 fileOfCards being that "slice" of structures of type charSetStruct

 i.e., We are creating a slice named fileOfCards that holds instances of the charSetStruct type

Each element in the slice is initialized using the composite literal syntax whereby
... we are providing values for each field of the charSetStruct struct: i.e.,
... each set of values enclosed in curly braces { ... } represents an instance of the struct.
*/

// Constants:
const colorReset = "\033[0m"
const colorRed = "\033[31m"
const colorGreen = "\033[32m"
const colorCyan = "\033[36m"
const colorPurple = "\033[35m"
